#!/usr/bin/env python

import sys
import os
from os.path import join as pathjoin

if os.getcwd().split('/')[-1] == 'scripts':
	sys.exit("Sorry, you have to run this script in the main path")

from setup import VERSION

distname = 'dist/solvatum-' + VERSION + '.tar.gz'

os.system('tar cfvz ' + distname + ' * --exclude scripts --exclude dist --exclude .git --exclude *.pyc --exclude solvatum/*.pyc --exclude solvatum/test.py --exclude .gitignore')
