#!/usr/bin/env python

import sys
import os
from os.path import join as pathjoin

if os.getcwd().split('/')[-1] == 'scripts':
	sys.exit("Sorry, you have to run this script in the main path")

from solvatum import __version__

distname = 'dist/solvatum-' + __version__ + '.tar.gz'

os.system('tar cfvz ' + distname + ' * --exclude scripts --exclude dist --exclude .git --exclude *.pyc --exclude solvatum/*.pyc --exclude .gitignore')


